services:

  postgres:
    image: postgres:16-alpine
    container_name: reco-postgres
    environment:
      POSTGRES_USER: reco_user
      POSTGRES_PASSWORD: reco_pass
      POSTGRES_DB: reco_db
    ports:
      - "5433:5432"  # Maps container port 5432 to host port 5433
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: reco-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  minio:
    image: quay.io/minio/minio
    container_name: reco-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # API port
      - "9001:9001"   # Console port
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  postgres-data:
  minio-data:
