-- custodian bank initial creation 03-06-2025
DROP TABLE IF EXISTS custodian_bank;

CREATE TABLE IF NOT EXISTS custodian_bank (
    id SERIAL PRIMARY KEY,
    account_number VARCHAR(50) NOT NULL,
    account_name VARCHAR(255) NOT NULL,
    cash_account_number VARCHAR(50) NOT NULL,
    cash_account_name VARCHAR(255) NOT NULL,
    reporting_currency_name VARCHAR(50) NOT NULL,
    local_currency_code VARCHAR(10) NOT NULL,
    local_currency_name VARCHAR(50) NOT NULL,
    location_code VARCHAR(50) NOT NULL,
    location_name VARCHAR(50) NOT NULL,
    cash_reporting_date DATE NOT NULL,
    settle_pay_date DATE,
    tax_code VARCHAR(25),
    transaction_type_code VARCHAR(25),
    transaction_type VARCHAR(100),
    main_transaction_code VARCHAR(25),
    sub_transaction_code VARCHAR(25),
    detailed_transaction_type_name VARCHAR(255),
    transaction_description_1 VARCHAR(255),
    transaction_description_3 VARCHAR(255),
    transaction_description_4 VARCHAR(255),
    transaction_description_5 VARCHAR(255),
    actual_settle_date DATE,
    alternate_delivery_date DATE,
    record_date DATE,
    cash_post_date DATE,
    cash_value_date DATE,
    shares_par DECIMAL(18,6),
    opening_balance_local DECIMAL(18,2),
    transaction_amount_local DECIMAL(18,2),
    closing_balance_local DECIMAL(18,2),
    transaction_amount_reporting_equivalent DECIMAL(18,2),
    begin_date DATE,
    end_date DATE,
    report_run_date DATE NOT NULL,
    report_run_time VARCHAR(50) NOT NULL,
    current_factor DECIMAL(18,6),
    previous_factor DECIMAL(18,6),
    event_id BIGINT,
    flat_tax_percent DECIMAL(5,2),
    flat_tax_amount DECIMAL(18,2),
    solidarity_percent DECIMAL(5,2),
    solidarity_amount DECIMAL(18,2),
    flat_tax_currency VARCHAR(10)
);
